### ISSUE TITLE
Graphql Server not connecting to room

### ISSUE THREAD

**Issue by chereseeriepa** [planetary-social/planetary-graphql#41]
Latest changes from https://github.com/planetary-social/planetary-graphql/pull/39 are preventing the graphql server from connecting to the room.

Steps to reproduce:
1. Pull down the latest changes
2. Install dependencies
3. Start the development server `npm run dev`

Expected:
- it to start and connect to the room

Actual:
- getting an error in the console:

```
server error, from net:127.0.0.1:50918~shs:
Error: shs.server: client hello invalid (phase 3). they dailed a wrong number - they didn't have our public key
    at abort (/Users/planetary/planetary-social/planetary-graphql/node_modules/secret-handshake/protocol.js:82:45)
    at Object.cb (/Users/planetary/planetary-social/planetary-graphql/node_modules/secret-handshake/protocol.js:96:20)
    at drain (/Users/planetary/planetary-social/planetary-graphql/node_modules/pull-reader/index.js:39:14)
    at more (/Users/planetary/planetary-social/planetary-graphql/node_modules/pull-reader/index.js:55:13)
    at /Users/planetary/planetary-social/planetary-graphql/node_modules/pull-reader/index.js:66:9
    at /Users/planetary/planetary-social/planetary-graphql/node_modules/pull-reader/index.js:20:7
    at drain (/Users/planetary/planetary-social/planetary-graphql/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/Users/planetary/planetary-social/planetary-graphql/node_modules/stream-to-pull-stream/index.js:135:5)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12) {
  address: 'net:127.0.0.1:50918~shs:'
}
failed to connect to room Error: shs.client: server hung up when we sent hello (phase 3).
    at clarify (/Users/planetary/planetary-social/planetary-graphql/node_modules/clarify-error/lib/index.js:11:24)
    at abort (/Users/planetary/planetary-social/planetary-graphql/node_modules/secret-handshake/protocol.js:37:45)
    at Object.cb (/Users/planetary/planetary-social/planetary-graphql/node_modules/secret-handshake/protocol.js:52:26)
    at drain (/Users/planetary/planetary-social/planetary-graphql/node_modules/pull-reader/index.js:43:23)
  Error: stream ended with:64 but wanted:80
    at drain (/Users/planetary/planetary-social/planetary-graphql/node_modules/pull-reader/index.js:43:26)
    at /Users/planetary/planetary-social/planetary-graphql/node_modules/pull-reader/index.js:63:18
    at /Users/planetary/planetary-social/planetary-graphql/node_modules/pull-reader/index.js:20:7
    at drain (/Users/planetary/planetary-social/planetary-graphql/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/Users/planetary/planetary-social/planetary-graphql/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  address: 'net:127.0.0.1:8008~shs:'
}
```

Other things I tried:
- deleting my database and start from a fresh one. I still saw this same error for the new database
- rewinding the room server to a commit where it was working, to confirm it wasnt the room. Confirmed it wasnt the room server
- rewinding to the commit before this PR, i no longer saw this issue
- readded the graphql server as member when i deleted the database
- printing out the multiserver address, it looked correct to me

**Comment by mixmix** [comment]
disabled incoming net: connections for now
These should not be needed as this is not a pub!
We do want to allow incoming tunnel connections though to communicate via the room
